### ISSUE TITLE
Integrate Codecov Test Analytics

### ISSUE THREAD

**Issue by anton-matosov** [Dr-QP/Dr.QP#31]
https://docs.codecov.com/docs/test-analytics

```

      - name: Upload test results to Codecov
        uses: codecov/test-results-action@v1
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          directory: build

```
