### ISSUE TITLE
Setup Micro Kubernetes on robot RPi and deploy to it

### ISSUE THREAD

**Issue by anton-matosov** [Dr-QP/Dr.QP#57]
Setup Kubernetes https://microk8s.io/
Add deployment jobs from GHA that deploy edge there

**Comment by anton-matosov** [comment]
```
apiVersion: apps/v1
kind: Deployment
metadata:
  name: dr-qp-control
  namespace: default
  labels:
    k8s-app: dr-qp-control
annotations:
  description: A Dr.QP ROS control node
spec:
  replicas: 1
  selector:
    matchLabels:
      k8s-app: dr-qp-control
  template:
    metadata:
      name: dr-qp-control
      labels:
        k8s-app: dr-qp-control
    annotations:
      description: A Dr.QP ROS control node
    spec:
      containers:
        - name: dr-qp-control
          image: ghcr.io/dr-qp/ros-deploy:edge
          imagePullPolicy: Always
          command:
            - /ros_entrypoint.sh
          args:
            - ros2 run drqp_control control walk
          securityContext:
            privileged: true
```
