### ISSUE TITLE
add cache for ROS CI and Devcontainer

### ISSUE THREAD

**Issue by anton-matosov** [Dr-QP/Dr.QP#66]

**Comment by anton-matosov** [comment]
https://github.com/ros-tooling/action-ros-ci/blob/v0.3/src/action-ros-ci.ts#L491C2-L493C33
```

	// Wipe out the workspace directory to ensure the workspace is always
	// identical.
	await io.rmRF(rosWorkspaceDir);
```

**Comment by anton-matosov** [comment]
```
        - name: Restore colcon build dirs
          id: cache-ros-ws-restore
          uses: actions/cache@v4
          with:
            path: |
              build
              install
            key: ${{ matrix.runner }}-ros_ws-${{ hashFiles('**/package.xml,**/CMakeFiles.txt,**/*.cmake') }}
            restore-keys: |
              ${{ matrix.runner }}-ros_ws-
```
